services:

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8081
    volumes:
      - ./:/usr/src/app
    ports:
      - '8081:8081'
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
  redis:
    image: "redis:latest"

volumes:
  postgres_data: